version: '3'
services:
 nginx:
  image: nginx:alpine
  restart: always
  ports:
   - ${NGINX_PORT}:80
  depends_on:
   - apache
  volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  networks:
   - core_cms_lampp_net
 
 apache:
  image: justinluong/php:7.2.5
  restart: always
  volumes:
   - ${SOURCE_CODE_DIR}:/var/www/html
   - ./apache2/apache2.conf:/etc/apache2/apache2.conf
   - ./apache2/ports.conf:/etc/apache2/ports.conf
   - ./apache2/http-vhosts.conf:/etc/apache2/http-vhosts.conf
   - ./php/php.ini:/usr/local/etc/php/php.ini
  networks:
   - core_cms_lampp_net
  
 
 mysql:
  image: mysql:5.7
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
  volumes:
   - ./mysql/data:/var/lib/mysql
  networks:
   - core_cms_lampp_net
  
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  restart: always
  depends_on: 
   - apache
   - mysql
   - nginx
  ports:
   - ${PHPMYADMIN_PORT}:80
  environment:
   - PMA_HOST=mysql
  networks:
   - core_cms_lampp_net

networks:
 core_cms_lampp_net:
